server:
  port: 50001

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://db:5432/test
    password: example
  flyway:
    enabled: false
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/test
    user: "postgres"
    password: "example"

logging:
  level:
    org:
      springframework:
        security: DEBUG

  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest
    queue:
      name: testqueue